apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubox
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: kubox
    spec:
      containers:
        - name: kubox
          image: zihao/play:kubox
          imagePullPolicy: Always
          command:
            - /kubox-init.sh
          volumeMounts:
            - mountPath: /home/kubox
              name: kubox
            - mountPath: /var/run/docker.sock
              name: docker-sock
          ports:
          - containerPort: 50022
            hostPort: 50022
            name: ssh
          - containerPort: 50023
            hostPort: 50023
            protocol: UDP
            name: mosh
      volumes:
        - name: kubox
          persistentVolumeClaim:
            claimName: kubox
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: kubox
#   labels:
#     app: kubox
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: kubox.zihao.me
#     external-dns.alpha.kubernetes.io/use-external-host-ip: "true"
# spec:
#   selector:
#     app: kubox
#   type: ClusterIP
#   clusterIP: None
