apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubox
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: kubox
    spec:
      containers:
        - name: kubox
          image: ubuntu:18.04
          imagePullPolicy: Always
          command:
            - sleep
          args:
            - infinity
          volumeMounts:
            - mountPath: /home/kubox
              name: kubox
            - mountPath: /var/run/docker.sock
              name: docker-sock
      volumes:
        - name: kubox
          persistentVolumeClaim:
            claimName: kubox
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
